# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://farnood.design
title: Farnood Foroudi
author: Farnood Foroudi
description: Product Designer, UI/UX Professional, Mobile Apps Enthusiast.
avatar: profile.png
email: foroudi@gmail.com
github: farnood
behance: farnood
twitter: farnood
linkedin: farnood
disqus: username
google_analytics: UA-69391421-1
